// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Sucursal_La_Paz_microservicio.Migrations
{
    [DbContext(typeof(SucursalLP_Context))]
    [Migration("20251114032145_v0")]
    partial class v0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.DetalleIngresoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodIngresoOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_ingreso_original");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<Guid>("IdReporteIngresoDiario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_reporte_ingreso_diario");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ingreso");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("DetalleIngresoDiario");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.GastoDiarioDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodGastoOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_gasto_original");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<Guid>("IdReporteGastoDiario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_reporte_gasto_diario");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<string>("TipoGasto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_gasto");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("GastoDiarioDetalle");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.ReporteGastoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodSucursal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_sucursal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("TotalGastosLaborales")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gastos_laborales");

                    b.Property<decimal>("TotalGastosOperativos")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gastos_operativos");

                    b.Property<decimal>("TotalOtrosGastos")
                        .HasColumnType("numeric")
                        .HasColumnName("total_otros_gastos");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("ReporteGastoDiario");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.ReporteIngresoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodSucursal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_sucursal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("TotalIngresoPorVentas")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ingreso_por_ventas");

                    b.Property<decimal>("TotalOtrosIngresos")
                        .HasColumnType("numeric")
                        .HasColumnName("total_otros_ingresos");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("ReporteIngresoDiario");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.ReporteInventarioDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_producto");

                    b.Property<string>("CodSucursal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_sucursal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("EntradaDelDia")
                        .HasColumnType("integer")
                        .HasColumnName("entrada_del_dia");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("SalidaDelDia")
                        .HasColumnType("integer")
                        .HasColumnName("salida_del_dia");

                    b.Property<int>("StockFinalDia")
                        .HasColumnType("integer")
                        .HasColumnName("stock_final_dia");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("ReporteInventarioDiario");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.ReporteRendimientoIndividual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodEmpleado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_empleado");

                    b.Property<string>("CodSucursal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_sucursal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateOnly>("FechaObservacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_observacion");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("ReporteRendimientoIndividual");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.ReporteRendimientoLaboralDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodSucursal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_sucursal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<decimal>("CostoLaboralTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_laboral_total");

                    b.Property<int>("EmpleadosActivos")
                        .HasColumnType("integer")
                        .HasColumnName("empleados_activos");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("HorasTrabajadasTotales")
                        .HasColumnType("numeric")
                        .HasColumnName("horas_trabajadas_totales");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("ReporteRendimientoLaboralDiario");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.ReporteVentaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CantidadPedidos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_pedidos");

                    b.Property<string>("CodSucursal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_sucursal");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("TotalProductosVendidos")
                        .HasColumnType("integer")
                        .HasColumnName("total_productos_vendidos");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ventas");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("ReporteVentaDiaria");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asunto");

                    b.Property<string>("CodAprobadorRechazador")
                        .HasColumnType("text")
                        .HasColumnName("codigo_aprobador_rechazador");

                    b.Property<string>("CodDestino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_destino");

                    b.Property<string>("CodSolicitante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_solicitante");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaAprobacionRechazo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_aprobacion_rechazo");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("JustificacionRechazo")
                        .HasColumnType("text")
                        .HasColumnName("justificacion_rechazo");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prioridad");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_solicitud");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("Sucursal_La_Paz_microservicio.Core.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("Sucursal");
                });
#pragma warning restore 612, 618
        }
    }
}
